services:
  - type: static
    name: orphan-registration-form
    env: static
    buildCommand: ""
    staticPublishPath: .
    repo: https://github.com/ITunitAlamal/orphan-registration-form
    branch: main